services:
  web:
    image: nginx
    ports:
      - 80:80
    volumes:
      - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - .:/var/www/html


  php-fpm:
    build:
      dockerfile: ./docker/Dockerfile
    environment:
      - APP_ENV=local
      - APP_KEY=base64:5sSiCEgdu9Y8sFKEnAc4hqubVozhoqJiqYNlZWmiPeY=
      - APP_DEBUG=true
      - APP_URL=http://localhost
    volumes:
      - .:/var/www/html
      - .:/docker/xdebug.ini:/usr/local/etc/php/conf.d/docker-php-xdebug.ini


  postgres:
    image: postgres:17.6
    volumes:
      - ./docker/postgres/data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=123
      - POSTGRES_DB=testdb

    ports:
      - 54321:5432
